language: python
python:
  - 3.6
env:
  - WITH_MPI=no
  - WITH_MPI=yes MPI4PY_VERSION=3.0.2 HDF5_VERSION=1.10.5 PNETCDF_VERSION=1.11.2 NETCDF4_VERSION=4.6.3 NETCDF4_PYTHON_VERSION=1.5.1.2
before_install:
  - source .travis.before_install.bash
install:
  - python -m pip install -r requirements.txt
  - python setup.py install
script:
  - if [ "$WITH_MPI" == "yes" ]; then python run-tests.py --verbose --full-trace -s; else pytest --verbose --full-trace -s; fi
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
